config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

  get 'categories/index'
  get '/signup', to:'users#new'
  get '/login', to: 'sessions#new'
  delete '/logout', to: 'sessions#destroy'
  
  resources :sessions
  resources :lessons, only: [:create, :show] do
    resources :answers, only: [:new, :create]
  end

  namespace :admin do 
    get '/home', to:'users#home'
    resources :users
    resources :categories do
      resources :words
    end
  end

  resources :relationships

  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :words, only: [:index]
end

app/models/activity.rb
class Activity < ApplicationRecord
  belongs_to :user
  belongs_to :action, polymorphic: true, dependent: :destroy

  has_one :activity, as: :action, dependent: :destroy
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :lesson
  belongs_to :word
  belongs_to :choice
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :words, dependent: :destroy
  has_many :lessons, dependent: :destroy

  validates :title, presence: true, length: {maximum: 50}
  validates :description, presence: true, length: {maximum: 150}
end

app/models/choice.rb
class Choice < ApplicationRecord
  belongs_to :word

  validates :content, presence: true, length: {maximum: 50}
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  belongs_to :user
  belongs_to :category
  has_many :answers
  has_many :words, through: :answers
  has_one :activity, as: :action, dependent: :destroy

  def next_word
    (category.words - words).first
  end

  def correct_answers
    self.answers.joins(:choice).where(choices: {is_correct: true})
  end
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
  validates :follower_id, presence: true
  validates :followed_id, presence: true
  has_one :activity, as: :action, dependent: :destroy
  after_create :relationship_activity

  private
    def relationship_activity
      create_activity(user: follower)
    end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :lessons, dependent: :destroy
  
  has_many :active_relationships, class_name: "Relationship",
    foreign_key: "follower_id",
    dependent: :destroy
  
  has_many :passive_relationships, class_name: "Relationship",
    foreign_key: "followed_id",
    dependent: :destroy

  has_many :following, through: :active_relationships,source: :followed
  has_many :followers, through: :passive_relationships,source: :follower
  has_many :activities
  has_many :answers, through: :lessons
  has_many :categories, through: :lessons


  has_secure_password
  before_save { email.downcase! }

  validates :name, presence: true, length: {maximum: 50}

  EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: {maximum: 255},
                                    format: {with: EMAIL_REGEX },
                                    uniqueness: {case_sensitive: false}

  validates :password, length: { minimum: 6 }, allow_nil: true
  
  mount_uploader :avatar, AvatarUploader

  def lesson_taken(category_id)
    lesson = lessons.find_by(category_id:category_id)
  end

  def follow(user)
    following << user
  end

  def unfollow(user)
    following.delete(user)
  end

  def following?(user)
    following.include?(user)
  end

  def dashboard_feed
    following_ids ="SELECT followed_id FROM relationships
                      WHERE follower_id = :user_id"
    Activity.where("user_id IN (#{ following_ids }) OR user_id = :user_id",
    following_ids: following_ids, user_id: id)
  end
end

app/models/word.rb
class Word < ApplicationRecord
  belongs_to :category
  has_many :choices, dependent: :destroy
  has_many :lessons, through: :answers
  accepts_nested_attributes_for :choices

  validates :content, presence: true, length: {maximum: 50}

  validate :has_one_correct_answer
  validate :has_unique_choices

  def correct_answer
    choices.find_by(is_correct: true).content
  end

  private
  def has_one_correct_answer
    if choices.select{ |choices| choices.is_correct? }.count != 1 
      return errors.add :base, "Must have one correct choice"
    end  
  end

  def has_unique_choices
    if choices.uniq { |choice| choice.content }.count < choices.length
      return errors.add :base, "Must have unique choices"
    end
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  def new
    @lesson = Lesson.find(params[:lesson_id])
    @category = Category.find_by(id: @lesson.category_id)

    if @lesson.next_word.nil?
      @lesson.create_activity(user: current_user)
      redirect_to lesson_url(@lesson.id)
    end
  end

  def create
    @lesson = Lesson.find(params[:lesson_id])
    @answer = @lesson.answers.build(answer_params)

    if @answer.save
      redirect_to new_lesson_answer_url(@lesson)
    else
      'new'
    end
  end

  private
  def answer_params
    params.require(:answer).permit(:word_id, :choice_id, :lesson_id)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    begin
    @feeds = current_user.dashboard_feed.paginate(page: params[:page], per_page: 10).order(created_at: :desc)
    rescue
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(users_params)

    if @user.save
      redirect_to root_url
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
    @feeds = @user.activities.paginate(page: params[:page], per_page: 10)
  end

  def index
    @users = User.paginate(page: params[:page], per_page: 10)
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    if @user.update(users_params)
      redirect_to @user
    else
      render 'edit'
    end
  end

  def logged_in_user
    unless logged_in?
      flash[:danger] = "Please log in"
      redirect_to login_url
    end
  end

  def following
    @title = "Following"
    @user = User.find(params[:id])
    @users = @user.following.paginate(page: params[:page], per_page: 10)

    render 'show_follow'
  end

  def followers
    @title = "Followers"
    @user = User.find(params[:id])
    @users = @user.followers.paginate(page: params[:page], per_page: 10)

    render 'show_follow'
  end

  private
  def users_params
    params.require(:user).permit(:name, :email, :password, :password_comfirmation, :avatar)
  end
end

app/controllers/words_controller.rb
class WordsController < ApplicationController
  def index
    @user = User.find(current_user.id)
    @answers = @user.answers.paginate(page: params[:page],per_page: 10)
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def logged_in?
    !current_user.nil?
  end

  def current_user?(user)
    user == current_user
  end  

  def current_user
    @current_user ||= User.find_by(id:session[:user_id])
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/words_helper.rb
module WordsHelper
end

app/views/static_pages/home.html.erb
<% if logged_in? %>
    <div class="bg-dark">
        <div class="container">
            <div class="row">
                <div class="col-md-4">
                    <div>
                        <div class="card mt-4" style="width: 20rem;">
                            <% if current_user.avatar? %>
                                <%= image_tag current_user.avatar.url , class: "profile-picture" %>
                            <% else%>
                                <%= image_tag 'image2.jpeg', class: "profile-picture"%>
                            <% end %>
                            <div class="card-body text-center">
                                <h5 class="card-title"><%= current_user.name %></h5>
                                <p class="card-text"><%= current_user.email %></p>
                            </div>
                            <ul class="list-group list-group-flush text-center">
                                <li class="list-group-item"><a href="<%= following_user_path(current_user)%>"><%= current_user.following.count %>Following</a></li>
                                <li class="list-group-item"><a href="<%= followers_user_path(current_user)%>"><%= current_user.followers.count %>Followers</a></li>
                                <% unless current_user == current_user%>
                                    <%= render 'follow_form' if logged_in? %>
                                <% end %>
                            </ul>
                            <div class="card-body text-center">
                                <% total = current_user.answers.count %>
                                <h4><%= link_to "Words Learned: #{total}", words_path %></h4>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-8 pt-3 text-black">
                    <div class ="card mt-2">
                        <div class ="card-header">Activities</div>
                        <div class ="card-body">
                            <div class="paginate text-center">
                                <%= will_paginate @feeds %> 
                            </div>
                            <%= render 'shared/feed' %>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
<% else %>
    <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
        <ol class="carousel-indicators">
            <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
        </ol>
        <div class="carousel-inner">
            <div class="carousel-item active">
                <%=image_tag 'code-2620118_1280.jpg', class:"d-block w-100", size:'736x650'%>
                <div class="carousel-caption d-none d-md-block" >
                    <h1>Welcome to Elearning</h1>
                    <p >Nulla vitae elit libero, a pharetra augue mollis interdum.</p>
                    <a class="btn btn-outline-success btn-lg" href="#">Get Started</a>
                </div>
            </div>
            <div class="carousel-item">
                <%=image_tag 'laptop-3187095_1280.jpg', class:"d-block w-100", size:'736x650' %>
            </div>
            <div class="carousel-item">
                <%= image_tag 'startup-593341_1280.jpg', class:"d-block w-100", size:'736x650'%>
            </div>
        </div>
        <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>
<% end %>