config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

  get 'categories/index'
  get '/signup', to:'users#new'
  get '/login', to: 'sessions#new'
  delete '/logout', to: 'sessions#destroy'
  
  resources :sessions
  resources :lessons, only: [:create, :show] do
    resources :answers, only: [:new, :create]
  end

  namespace :admin do 
    get '/home', to:'users#home'
    resources :users
    resources :categories do
      resources :words
    end
  end

  resources :relationships

  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :words, only: [:index]
end

app/models/word.rb
class Word < ApplicationRecord
  belongs_to :category
  has_many :choices, dependent: :destroy
  has_many :lessons, through: :answers
  accepts_nested_attributes_for :choices

  validates :content, presence: true, length: {maximum: 50}

  validate :has_one_correct_answer
  validate :has_unique_choices

  def correct_answer
    choices.find_by(is_correct: true).content
  end

  private
  def has_one_correct_answer
    if choices.select{ |choices| choices.is_correct? }.count != 1 
      return errors.add :base, "Must have one correct choice"
    end  
  end

  def has_unique_choices
    if choices.uniq { |choice| choice.content }.count < choices.length
      return errors.add :base, "Must have unique choices"
    end
  end
end

app/controllers/admin/words_controller.rb
class Admin::WordsController < ApplicationController
  def index
    @category = Category.find(params[:category_id])
    @words = @category.words
  end

  def new
    @category = Category.find(params[:category_id])
    @word = @category.words.build
    3.times { @word.choices.build }
  end

  def create
    @category = Category.find(params[:category_id])
    @word = @category.words.build(word_params)

    if @word.save
      flash[:success] = "Successfully created word"
      redirect_to admin_category_words_url
    else
      render 'new'
    end
  end

  def edit
    @word = Word.find(params[:id])
    @category = Category.find(params[:category_id])
  end

  def update
    @word= Word.find(params[:id])
    
    if @word.update(word_params)
      flash[:success] = "Word successfully updated"
      redirect_to admin_category_words_url
    else
      render 'edit'
    end
  end

  def destroy
    @word = Word.find(params[:id])
    @word.destroy

    redirect_to admin_category_words_url
  end
  
  private
  def word_params
    params.require(:word).permit(:content, choices_attributes: [:id, :content, :is_correct])
  end
end

app/controllers/words_controller.rb
class WordsController < ApplicationController
  def index
    @user = User.find(current_user.id)
    @answers = @user.answers.paginate(page: params[:page],per_page: 10)
  end
end

app/helpers/admin/words_helper.rb
module Admin::WordsHelper
end

app/helpers/words_helper.rb
module WordsHelper
end

app/views/admin/words/_form.html.erb
<%= form_for [:admin, @category, @word] do |f| %>
    <%= render "shared/error_messages", object: @word %>
    <div class="form-group">
        <%= f.label :content, "Word" %>
        <%= f.text_field :content, class: "form-control" %>
    </div>

    <div class="form-group">
        <%= label_tag "Choices" %>
        <%= f.fields_for :choices do |choice| %>
            <%= choice.text_field :content, class: "form-control" %>
            <%= choice.check_box :is_correct, class: "d-inline" %>
            <p class="d-inline">This is the answer!</p>
        <% end %>
    </div>

    <%= f.submit 'Create new words', class: "btn btn-dark btn-block" %>
<% end %>

app/views/admin/words/edit.html.erb
<div class="row categories">
    <div class="col-4 offset-4 mt-5">
        <h1 class="text-center">Edit word</h1>
        <br>
        <%= render 'form', btn_msg: "Update word" %>
        <br>
        <%= link_to 'Back', admin_categories_path, class: "back-btn" %>   
    </div>
</div>

app/views/admin/words/index.html.erb
<div class="row">
    <div class="col-4 offset-4 mt-5">
        <h1 class="text-center title"><%= @category.title %></h1>
        <h4 class="text-center"><%= @category.description %></h4>
        <br>
        <div class="container text-center">
            <div class="btn-design">
                <%= link_to 'New words', new_admin_category_word_path, class: "btn btn-dark btn-lg" %>
            </div>
            <table class="table mt-3 table-bordered">
                <thead class="thead-dark">
                    <tr>
                        <th scope="col">Word</th>
                        <th scope="col">Answer</th>
                        <th scope="col">Settings</th>
                    </tr>
                </thead>
                <tbody>
                    <% @words.each do |word| %>
                        <tr>
                            <td><%= word.content %></td>
                            <td><%= word.correct_answer %></td>
                            <td>
                                <%= link_to 'Edit', edit_admin_category_word_path(@category, word) %> /
                                <%= link_to 'Delete', admin_category_word_path(@category, word), method: :delete, data: { confirm: "Are your sure?"} %>
                            </td>
                        </tr>
                    <% end %>
                </tbody>
            </table>
            <%= link_to 'Back', admin_categories_path, class: "back-btn" %>
        </div>  
    </div>
</div>

app/views/admin/words/new.html.erb
<div class="row">
    <div class="col-4 offset-4 mt-5">
        <h1 class="text-center">New words</h1>
        <br>
        <%= render "form" %>
        <br>
        <%= link_to 'Back', admin_category_words_path, class: "back-btn" %>
    </div>
</div>