config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

  get 'categories/index'
  get '/signup', to:'users#new'
  get '/login', to: 'sessions#new'
  delete '/logout', to: 'sessions#destroy'
  
  resources :sessions
  resources :lessons, only: [:create, :show] do
    resources :answers, only: [:new, :create]
  end

  namespace :admin do 
    get '/home', to:'users#home'
    resources :users
    resources :categories do
      resources :words
    end
  end

  resources :relationships

  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :words, only: [:index]
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :words, dependent: :destroy
  has_many :lessons, dependent: :destroy

  validates :title, presence: true, length: {maximum: 50}
  validates :description, presence: true, length: {maximum: 150}
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController
  def new
    @category = Category.new
  end

  def create
    @category = Category.new(categories_params)
    
    if @category.save
      flash[:success] = "Category successfully created"
      redirect_to admin_categories_url
    else
      render 'new'
    end 
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    
    if @category.update(categories_params)
      redirect_to admin_categories_url
    else
      render 'edit'
    end
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy

    redirect_to admin_categories_url
  end

  def index
    @categories = Category.paginate(page: params[:page], per_page: 10)
  end

  private
  def categories_params
    params.require(:category).permit(:title, :description)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.paginate(page: params[:page], per_page: 6)
    @lesson = Lesson.new
    @user = User.find(current_user.id)

    if params[:learned] == "1"
      @categories = @user.categories.paginate(page: params[:page], per_page:10)
    elsif params[:learned] == "0"
      @categories = @categories.where.not(id:@user.category_ids).paginate(page: params[:page], per_page:10)
    end
  end
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/admin/categories/_form.html.erb
<%= form_for [:admin, @category] do |f| %>
    <%= render "shared/error_messages", object: @category %>
    <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: "form-control" %>
    </div>
    
    <div class="form-group">
        <%= f.label :description %>
        <%= f.text_area :description, size: '48x3' %>
    </div>

    <div class="actions">
        <%= f.submit btn_msg, class: "btn btn-dark btn-block" %>
    </div>
<% end %>

app/views/admin/categories/edit.html.erb
<div class="row categories">
    <div class="col-4 offset-4 mt-5">
        <h1 class="text-center">Edit category</h1>
        <br>
        <%= render 'form', btn_msg: "Update category" %>
        <br>
        <%= link_to 'Back', admin_categories_path, class: "back-btn" %>   
    </div>
</div>

app/views/admin/categories/index.html.erb
<div class="row">
    <div class="col-6 offset-3 mt-5 text-center">
        <h1>Adminiser categories</h1>
        <%= link_to "New category", new_admin_category_path , class: "btn btn-dark btn-lg"%>

        <table class="table mt-3 table-bordered">
            <thead class="thead-dark">
                <tr>
                    <th scope="col">Title</th>
                    <th scope="col">Description</th>
                    <th scope="col">Settings</th>
                </tr>
            </thead>
            <tbody>
                <% @categories.each do |category| %>
                    <tr>
                        <td><%= link_to category.title, admin_category_words_path(category) %></td>
                        <td><%= category.description %></td>
                        <td>
                            <%= link_to 'Edit', edit_admin_category_path(category) %> /
                            <%= link_to 'Delete', admin_category_path(category), method: :delete, data: { confirm: "Are your sure?"} %>
                        </td>
                    </tr>
                <% end %>
            </tbody>
        </table>
        <%= link_to 'Back', admin_home_path, class: "back-btn" %>
    </div>    
</div>

<div class="paginate text-center">
    <%= will_paginate %>
</div>

app/views/admin/categories/new.html.erb
<div class="row categories">
    <div class="col-4 offset-4 mt-5">
        <h1 class="text-center">New category</h1>
        <br>
        <%= render 'form', btn_msg: "Create a new category" %>
        <br>
        <%= link_to 'Back', admin_categories_path, class: "back-btn" %>   
    </div>
</div>