config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

  get 'categories/index'
  get '/signup', to:'users#new'
  get '/login', to: 'sessions#new'
  delete '/logout', to: 'sessions#destroy'
  
  resources :sessions
  resources :lessons, only: [:create, :show] do
    resources :answers, only: [:new, :create]
  end

  namespace :admin do 
    get '/home', to:'users#home'
    resources :users
    resources :categories do
      resources :words
    end
  end

  resources :relationships

  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :words, only: [:index]
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :words, dependent: :destroy
  has_many :lessons, dependent: :destroy

  validates :title, presence: true, length: {maximum: 50}
  validates :description, presence: true, length: {maximum: 150}
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController
  def new
    @category = Category.new
  end

  def create
    @category = Category.new(categories_params)
    
    if @category.save
      flash[:success] = "Category successfully created"
      redirect_to admin_categories_url
    else
      render 'new'
    end 
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    
    if @category.update(categories_params)
      redirect_to admin_categories_url
    else
      render 'edit'
    end
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy

    redirect_to admin_categories_url
  end

  def index
    @categories = Category.paginate(page: params[:page], per_page: 10)
  end

  private
  def categories_params
    params.require(:category).permit(:title, :description)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.paginate(page: params[:page], per_page: 6)
    @lesson = Lesson.new
    @user = User.find(current_user.id)

    if params[:learned] == "1"
      @categories = @user.categories.paginate(page: params[:page], per_page:10)
    elsif params[:learned] == "0"
      @categories = @categories.where.not(id:@user.category_ids).paginate(page: params[:page], per_page:10)
    end
  end
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/index.html.erb
<div class="text-center mb-3">
    <div class="row">
        <div class="col-6 offset-3 mt-5 text-center">
            <h1>Lessons</h1>
            <ul class="nav nav-pills nav-tabs justify-content-center mt-4">
                <li class="nav-item tab_settings">
                    <%= link_to "All", categories_index_path , class: "nav-link active"%>
                </li>
                <li class="nav-item tab_settings">
                    <%= link_to "Learned", categories_index_path(learned: "1") , class: "nav-link"%>
                </li>
                <li class="nav-item tab_settings">
                    <%= link_to "Not Learned", categories_index_path(learned: "0") , class: "nav-link"%>
                </li>
            </ul>
            <br>
            <% @categories.each do |category| %>
                <div class="row mb-2 d-inline-block w-50">
                    <% unless category.words.empty? %>
                        <% lesson = @user.lesson_taken(category.id) %>
                        <div class="col">
                            <div class="row no-gutters border rounded overflow-hidden flex-md-row mb-2 shadow-sm h-md-250 position-relative">
                                <div class="col p-4 d-flex flex-column position-static">
                                    <div class="text-left">
                                        <%= category.title %>
                                    </div>
                                    <div class="text-left">
                                        <%= category.description %>
                                    </div>
                                    <br>
                                    <br>
                                    <div class="text-right">
                                    <%#= hidden_field_tag @result =  %>
                                        <%= form_for @lesson do |f| %>
                                            <%= hidden_field_tag :category_id, category.id %>
                                            <% if lesson.nil? %>
                                                <%= f.submit "Learn", class: "btn btn-outline-dark text-right"%>
                                            <% else %>
                                                <%= link_to "Result",lesson , class: "btn btn-outline-dark text-right"%>
                                            <% end %>
                                        <% end %> 
                                    </div> 
                                </div>
                            </div>
                        </div>
                    <% end %>
                </div>
            <% end %>
        </div>    
    </div>

    <div class="paginate text-center">
        <%= will_paginate %> 
    </div>
    <%= link_to 'Back', admin_home_path, class: "back-btn" %>
</div>